/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdbool.h>
#include "stm32c031.h"
#include "../drivers/gpio.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


bool Pressed;

int main(void)
{

	GPIO_HANDLE_t SigOut;
	SigOut.pGPIOx = GPIOB;
	SigOut.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_11;//Pin 11 is chosen per the docs as this is an IO
	SigOut.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	SigOut.GPIO_PinConfig.GPIO_PinOPType = GPIO_OPTYPE_PP;
	SigOut.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_NO;
	SigOut.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;

	GPIO_HANDLE_t UserButton;
	UserButton.pGPIOx = GPIOB;
	UserButton.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_13;
	UserButton.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_IN;
	UserButton.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_PUPDR_PU;
	UserButton.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_LOW;
	GPIO_PeriClockControl(GPIOB,ENABLE);

	GPIO_Init(&SigOut);
	GPIO_Init(&UserButton);

	while(1){

	}

}
